version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "ScarVite"
      - "IchiiDev"
    commit-message:
      prefix: "🔼"
    labels:
      - "dependencies"
    open-pull-requests-limit: 15
