version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "ScarVite"
    commit-message:
      prefix: "🔼"
      prefix-develop: "🔼"
    labels:
      - "dependencies"
    open-pull-requests-limit: 15
