name: Deploy
on:
  push:
    branches: master
    paths:
      - "*"
    paths-ignore:
    - '**.md'
jobs:
  DePloY:
    runs-on: ubuntu-18.04
    steps:
      - name: Deploying...
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IPHOST }}
          username: ${{ secrets.SSHUSERNAME }}
          password: ${{ secrets.SSHPASSWORD }}
          script: |
            pm2 stop hse-manager-bot
            cd /data/bots/hse-manager
            git reset --hard
            git pull
            npm install
            pm2 reload hse-manager-bot
